language: node_js
node_js:
  - "6"
sudo: required
dist: trusty
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
branches:
  only:
    - master
before_script:
  - echo "start building"

