language: node_js
node_js:
  - "6"
sudo: required
dist: trusty
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - google-chrome
    packages:
      - g++-4.8
      - google-chrome-stable
cache:
  apt: true
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
before_script:
  - npm install -g selenium-standalone
  - xvfb-run --server-args="-screen 0, 1680x1050x24" selenium-standalone start > selenium.txt &
  - sleep 5
script:
  - npm test
  - npm run e2e

