language: node_js
node_js:
  - "6"
sudo: required
services:
  - docker
dist: xenial
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  apt: true
  yarn: true
  directories:
    - node_modules
branches:
  only:
    - master
before_install:
  - docker pull elgalu/selenium
  - docker run -d --name grid -p 4444:24444 -p 5900:25900 -e TZ="US/Central" --shm-size=1g elgalu/selenium
before_script:
  - nohup npm run server:dev > /dev/null &
script:
  - npm test
  - npm run e2e

